### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by christiantakle**
Added solutions to issues I had when running  `./run`

`patch` could be added to `apk` by default instead.

### CODE REVIEW

**Comment by Robertof** [comment]
Hey there! Thanks so much for the contribution!

Weird, so you had to install `patch` manually? I am pretty sure that the `busybox` bundled in `alpine` has it by default -- could it have been due to the fact that you had a pre-existing Docker image? I would have thought that using the `:latest` tag would have prompted Docker to download a fresh one but it looks like that might not be the case 🤔

**Comment by Robertof** [comment]
FWIW I just tested on my local machine just to be extra sure:

```
# docker run -it --rm alpine:latest
/ # which patch
/usr/bin/patch
/ # apk add git; git clone --depth=1 https://github.com/nixos/nixpkgs
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/6) Installing ca-certificates (20191127-r1)
(2/6) Installing nghttp2-libs (1.40.0-r0)
(3/6) Installing libcurl (7.67.0-r0)
(4/6) Installing expat (2.2.9-r1)
(5/6) Installing pcre2 (10.34-r1)
(6/6) Installing git (2.24.3-r0)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
OK: 22 MiB in 20 packages
Cloning into 'nixpkgs'...
remote: Enumerating objects: 35752, done.
remote: Counting objects: 100% (35752/35752), done.
remote: Compressing objects: 100% (24137/24137), done.
remote: Total 35752 (delta 793), reused 25580 (delta 487), pack-reused 0
Receiving objects: 100% (35752/35752), 23.07 MiB | 12.38 MiB/s, done.
Resolving deltas: 100% (793/793), done.
Updating files: 100% (21806/21806), done.
/ # wget https://raw.githubusercontent.com/Robertof/nixos-docker-sd-image-builder/master/docker/build-nixos/disable-zfs.patch
Connecting to raw.githubusercontent.com (151.101.192.133:443)
saving to 'disable-zfs.patch'
disable-zfs.patch    100% |********************************************************************************************************************************************************|   421  0:00:00 ETA
'disable-zfs.patch' saved
/ # cd nixpkgs/
/nixpkgs # patch nixos/modules/profiles/base.nix /disable-zfs.patch
patching file nixos/modules/profiles/base.nix
/nixpkgs # grep zfs nixos/modules/profiles/base.nix
/nixpkgs #
```

Do you have `patch` missing if you run `docker run -it --rm alpine:latest`?

**Comment by christiantakle** [comment]
Interesting. Yeah I am missing `patch`.
```
➜  ~ docker run -it --rm alpine:latest
/ # which patch
/ #
```
 Might be MacOS specific. I remove all my images to make sure I didn't have some weird interference.

```
➜  ~ docker --version
Docker version 19.03.8, build afacb8b
```

**Comment by Robertof** [comment]
Definitely very interesting! Thanks for getting back.

At this point I think it will be safer and easier to just add `patch` to the list of dependencies downloaded via `apk`, here:

https://github.com/Robertof/nixos-docker-sd-image-builder/blob/0a5cd7c10ac514e20c78ff2abc19996736a3ecc7/docker/build-nixos/Dockerfile#L10

It would be awesome if you could do that in your PR and then get rid of the change in README which suggests to do that, at least in this way it will just work.

If it's too much of an hassle I'll take care of it, just let me know. Thanks!

**Comment by christiantakle** [comment]
> I would have thought that using the :latest tag would have prompted Docker to download a fresh one but it looks like that might not be the case

Agree was hesitant to write anything about it since it might just be my system.

When I ran `./run` I first got the `zstd` error which was fixed by delete my previous alpine image. 
and then I started hitting the `patch` error.

Maybe update the the readme to include it as a MacOS troubleshooting.

## Unrelated 
Did get much further with the project today though. Tried booting the resulting image on the rpi 4 8gb. Where I get an error. I might open an issue later (didn't have time to investigate) and then I put the card into my rpi 4 4gb which was permanently stuck on the rainbow screen.

I might try to make a build on a linux-box later to check if there is just something wrong with my machine.

**Comment by christiantakle** [comment]
I will make the changes now

**Comment by Robertof** [comment]
Thanks a lot!

Regarding your issues, I think you are probably one of the first attempting to run NixOS on a Pi 4 8 GiB, and to be fair I'm not sure if there might be the need for an update to the RPi kernel.
It might be worth reporting your findings in [the Raspberry Pi 4 support thread on `nixpkgs`](https://github.com/NixOS/nixpkgs/issues/63720) when we determine more info on why it's possibly not working.

Other than that, at least the 4 GiB model should definitely not get stuck on the rainbow screen -- how did you flash the image onto the SD card? Happy to move the discussion on another issue if we want to close this 👍

**Comment by christiantakle** [comment]
If you are happy with the current change lets close this issue.

> how did you flash the image onto the SD card?
I was lazy and used [balenaEtcher](https://www.balena.io/etcher). I will do a second attempt with `dd` if that doesn't work then I will open a new issue.

**Comment by Robertof** [comment]
This is what I used at the time to flash the image for my Pi 3 if it helps:

`sudo gdd if=nixos*.img of=/dev/rdisk2 bs=64K status=progress`

(using `dd` from the `coreutils` package of homebrew, but the default one should also suffice)

Hopefully you'll get it sorted! Thanks again for the contribution.

**Pull request merged**
